### ISSUE TITLE
Look at GLyphy to render glyphs on GPU?

### ISSUE THREAD

**Issue by madig** [glennw/webrender#1]
(Not quite sure how to contact you, so here goes:)

Behdad Esfahbod wrote this little lib here: https://github.com/behdad/glyphy

Maybe this fits your project better than FreeType?

**Comment by pcwalton** [comment]
I've looked into this and the setup needed to convert beziers to arcs ends up way slower at small glyph sizes for initial pageload. We need some sort of alternate approach to generate the signed distance fields. (That approach could be "ship precomputed SDFs for common Web fonts", BTW.)

**Comment by madig** [comment]
(I just have to leave this here: http://wdobbie.com/post/gpu-text-rendering-with-vector-textures/)
