### ISSUE TITLE
box-shadow not correctly rendered

### ISSUE THREAD

**Issue by paulrouget** [glennw/webrender#156]
```html
<div style="height: 400px; width: 400px; margin: 100px; box-shadow: -80px -80px 80px black">
</div>
```

<img width="850" alt="screen shot 2016-01-29 at 04 43 28" src="https://cloud.githubusercontent.com/assets/373579/12666636/e4241e34-c642-11e5-9b28-7123daf2da9e.png">

Script highlighting the blurring value issue:

```html
<div style="height: 400px; width: 400px; margin: 100px; box-shadow: -80px -80px 0px black">
</div>

<script>
  var s = 0;
  setInterval(() => {
    s++;
    document.querySelector("div").style.boxShadow = `-80px -80px ${s}px black`;
    document.querySelector("div").textContent = s;
  }, 100);
</script>
```

**Comment by glennw** [comment]
@paulrouget Would you mind checking this again? I don't see the missing parts of the box shadow with current WR, if that's what you're referring to?

**Comment by paulrouget** [comment]
Works for me now.
