### ISSUE TITLE
Creating VBOs spends an inordinate amount of time in round()

### ISSUE THREAD

**Issue by pcwalton** [glennw/webrender#16]
Like, at least 20% of the time spent in rendering is spent in roundf(), probably more.

Do we really need to round when converting floating point to fixed point that way?

**Comment by glennw** [comment]
I plan to do some experiments and profiling with vertex formats next week, there's definitely some easy wins to be had there.

**Comment by glennw** [comment]
Are you able to run the same profiling again and see how much the rounding costs now? If it's still expensive, we could look at rounding the positions in the vertex shader (and potentially uploading the UVs un-normalized and rounding them in the vertex shader too).

**Comment by pcwalton** [comment]
Looks fixed now. :)
