### ISSUE TITLE
Gradient not painted correctly

### ISSUE THREAD

**Issue by paulrouget** [glennw/webrender#161]
```html
<style>
  div {
    width: 50px;
    height: 50px;
    background-color: #00f;
    margin: 20px;
  }
</style>

<div style="background-image: linear-gradient(135deg, #F00 50%, transparent 50%)"></div>
<div style="background-image: linear-gradient(135deg, #F00,     transparent 50%)"></div>
```

<img width="523" alt="screen shot 2016-02-01 at 11 31 19" src="https://cloud.githubusercontent.com/assets/373579/12714921/99f3406e-c8d7-11e5-9564-c809eccb0ced.png">

**Comment by pcwalton** [comment]
Yeah, this is the issue whereby we don't tessellate axis aligned gradients.

I now feel like the best solution to this problem may be to just use the upgraded clip rect infrastructure, when we have it—i.e. clip out in the fragment shader. That will depend on a bit of infrastructure we don't yet have, though: the matrix/clip stack.

@paulrouget, would it be better if I rendered the gradient outside the box for now until we have that infrastructure? I can do that real quick if that's an improvement.

**Comment by pcwalton** [comment]
Dependency: #154.

**Comment by paulrouget** [comment]
> @paulrouget, would it be better if I rendered the gradient correctly, but spilling outside the box, for now until we have that infrastructure? I can do that real quick if that's an improvement.

Spilling will be a problem too.

We can use a PNG instead of a linear-gradient for now.

**Comment by paulrouget** [comment]
P1 -> P2. Browserhtml workaround: https://github.com/mozilla/browser.html/issues/861

**Comment by pcwalton** [comment]
Actually, I'll fix it for real. :)

**Comment by pcwalton** [comment]
@paulrouget I have a fix ready. Sorry for making you go through the work of making a PNG workaround.

**Comment by paulrouget** [comment]
This doesn't appear to be fixed.

I see this now:

![Uploading Screen Shot 2016-02-03 at 06.50.46.png…]()
