### ISSUE TITLE
How to build and run?

### ISSUE THREAD

**Issue by yohanesu75** [glennw/webrender#192]
Hi

Great work! How can I build and run this? Is it a standalone binary or plugin to Servo?

I'm on Arch Linux with Rust nightly from 2016-02-09 and getting build error on dependencies (different depending on Rust version...)

**Comment by ecoal95** [comment]
Since a few days ago you can run servo with the `-w` switch, and it will use webrender :P

**Comment by paulrouget** [comment]
> Is it a standalone binary or plugin to Servo?

It's part of Servo. Compile [Servo](http://github.com/servo/servo) and run it with the `-w` option.
