### ISSUE TITLE
Some documentation of the chromium implementation. 

### ISSUE THREAD

**Issue by LifeIsStrange** [glennw/webrender#41]
The blinks devs already try to use the gpu for drawing, see here some documentation : https://www.chromium.org/developers/design-documents/gpu-accelerated-compositing-in-chrome
But their implementation seems less ambitions ;) 
Sorry if I have said something of stupid.

**Comment by pcwalton** [comment]
This would be better placed on the wiki. Thanks for the info though!

**Comment by LifeIsStrange** [comment]
Oh sorry I don't knew that I could modifiate the wiki, I know very bad how work github. 
Also sorry if my implementation in the wiki is bad, I speak bad english. 
Thanks for your awesome works free software devs :).

**Comment by LifeIsStrange** [comment]
I have create a new page on the wiki where contributors can add useful documentation for you and us.
