### ISSUE TITLE
Too many vertices with tiled backgrounds on large pages

### ISSUE THREAD

**Issue by pcwalton** [glennw/webrender#47]
Example page: https://miiverse.nintendo.net/guide/

This page creates 35,346 tilings of the background image, since we have a 12x12 background tiled to a layer of 1024x4931. Every time the root stacking context is updated, we recreate the tiles for the entire layer. This slows WebRender to a crawl, even with some optimizations I'm about to land.

The obvious way to fix this would be to only tile inside the screen rect. This would reduce the number of tilings to about 5,500. Is this compatible with the batch caching design?

Another possible approach is to break up large tiled images to a few medium-sized areas in the AABB tree, so that we can more aggressively cull outside the visible area.

Yet another way to fix this would be to pre-cache a few repeats of repeating backgrounds a bit to reduce the number of tiles that have to be drawn. I don't like this approach much because it wastes memory, increases load on the rasterizer, and it doesn't really solve the problem in the general case.

Last, we could have a special shader for large tiled backgrounds. This is a last resort, though, because it will either break our batching or complicate the quad shader.

**Comment by glennw** [comment]
```Another possible approach is to break up large tiled images to a few medium-sized areas in the AABB tree, so that we can more aggressively cull outside the visible area.```

I think this is probably the right approach - we should test that and see how easily it fits in.
