### ISSUE TITLE
Add WebGL support

### ISSUE THREAD

**Issue by ecoal95** [glennw/webrender#73]
This is a meta-issue to discuss possible WebGL implementations with WebRender.

The first idea I had was keeping the WebGL task as-is, with the context sharing resources with the WebGL context, but that could be racy (that could be manually fixed though) as well as non-performant.

Another idea was to keep the same approach as now, but sending `NativeSurface`s to WebRender. The WebRender context would re-bind the surface to a texture, and paint using that texture. It seems to me that it will work, avoiding the roundrip to main memory (I think that at least in GLX the texture will get the contents of the surface, and probably in other platforms too).

Glenn also suggested using the WebGL task as a command proxy, and do all the paint work in WebRender, avoiding any resource sharing to avoid using context sharing (which is an uncommon code path). In my opinion this won't work out well, since it also adds a lot of complexity, since WebRender would be responsible of keeping each WebGL context *state* separately (that includes a lot of non-trivial state such as viewport, etc.), and restoring the WebRender state, wich will be a considerable overhead.

That got me to think though, that the latter approach, combined with resource sharing could be the best option: Sharing resources between the contexts, using the WebGL task as a proxy (or even taking rid of it), but keeping the contexts in WebRender, and only executing gl commands when required.

Since I probably didn't explain myself very well, this would be an sketch of the proposed implementation:

* When a WebGL context is (trying to be) created, the WebGL paint task requests WebRender to create a context.
* WebRender creates a new gl context, sharing resources with the main context, associates it with an unique id and returns that id (or the error, if that's the case) to the WebGL task.
* The WebGL task just serializes the gl commands received from script in a form like `(context_id, command)`.
* WebRender, before painting, takes that commands, sorts them by context id (to minimize context switching), and applies them to the given context. Note that there are special commands that need a reply from our side, like creating resources. When they arrive we could either do nothing until the next paint, when it will be processed, or flush the command buffer executing all the previous commands. The former is arguably simpler, but will make creating resources really slow, so I'd go for flushing the command buffer.
* WebRender does the actual paint, using the shared texture id's from the contexts.

I think this approach will be at least as performant as any other multithreaded approach, since most (if not all) the OpenGL implementations are single threaded, and this approach minimizes context switching, and prevents any kind of races that could be between WebRender and WebGL.

Note that the WebGL contexts should draw to a texture, but that's already done in the current implementation.

Also the WebGL task would be kind of naive with this scheme, so we could get rid of it easily I think.

I'd want to get some feedback or other ideas about this, and I could try to prototype it in the following weeks.

cc: @mrobinson @pcwalton @glennw

**Comment by pcwalton** [comment]
I had assumed we would just send native surfaces for now to get WR landed, and then perhaps follow up with a more complex scheme like the one you described later.

**Comment by ecoal95** [comment]
If the priority is to get it landed soon, I guess it would be easier to use the same scheme that the 2d canvas is using right now, am I right?

**Comment by LifeIsStrange** [comment]
But it's a very big work which will be obscolete because we will need replace webgl by Vulkan. 
Vulkan is espected to be released in december so why not wait ? When servo will be stable, all the mainstream public will have driver Vulkan ready :)

**Comment by glennw** [comment]
I think getting the basic surfaces sent across would be good for now - which will allow us to pass the tests and get it landed. But it's definitely worth doing some experiments with the ideas mentioned above to get it performing well.
