### ISSUE TITLE
Make a developers call ? 

### ISSUE THREAD

**Issue by LifeIsStrange** [glennw/webrender#87]
From what I understund, webrender play a major performance and efficiency role on servo but it has only 2 developpers ! 
I think that because webrender is a priority,you should do a developpers call on the servo github,it's Just an idea from Just a mozilla fan so maybe I say something of stupid.

**Comment by pcwalton** [comment]
We're definitely very happy to have new contributors :)

I think the issue tracker is not the right place for this, though; the Servo mailing list would be more appropriate.

**Comment by LifeIsStrange** [comment]
Yes you are right, you want to do this ? :)

**Comment by glennw** [comment]
We'll be merging this soon, which should make it easier for others to contribute :)
