### ISSUE TITLE
Make use of openCL ? 

### ISSUE THREAD

**Issue by LifeIsStrange** [glennw/webrender#92]
I think there is possible use case of openCL on webrender. 

Gimp 2.10 for exemple will use for render images : http://fr.slideshare.net/mobile/lgworld/implementing-opencl-support-in-gegl-and-gimp

Even libreoffice now use opencl :
http://developer.amd.com/community/blog/2015/07/15/collaboration-and-open-source-at-amd-libreoffice/
And it's a contribution from AMD, so I think that if there is use case of openCL on servo/webrender you should ask to AMD to help you. 

Also amd will in the near future open source it's openCL 2.0 implementation so all opensource drivers will probably benefit of this.

**Comment by pcwalton** [comment]
I think I would prefer OpenGL Compute Shader to OpenCL. But we need to find a good specific area to use compute shaders first before we even start thinking about it.
